version: '3.7'
services:
  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./:/var/www/:delegated
      - ./docker/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - db

  php:
    image: php:7.3.16-fpm
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/:delegated
      - ./docker/php.ini:/usr/local/etc/php/php.ini

  cli:
    image: wordpress:cli
    volumes:
      - ./:/var/www/
    depends_on:
      - php
      - db
    entrypoint: wp
    command: "--info"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_local'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./docker/db:/var/lib/mysql:delegated
